import { Barangay, Coordinator } from "./types";

export const mockBarangays: Barangay[] = [
  {
    id: "brgy-001",
    name: "San Antonio",
    districtId: "dist-01",
    districtName: "North District",
    population: 15203,
    votingPopulation: 8904,
    favoredVotePct: 62.5,
    isWin: true,
    congVisitCount: 3,
    coordinatorUids: ["coord-01", "coord-02"],
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: "brgy-002",
    name: "Poblacion",
    districtId: "dist-02",
    districtName: "Urban District",
    population: 22450,
    votingPopulation: 15100,
    favoredVotePct: 48.2,
    isWin: false,
    congVisitCount: 5,
    coordinatorUids: ["coord-03"],
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: "brgy-003",
    name: "Santa Cruz",
    districtId: "dist-03",
    districtName: "East District",
    population: 8900,
    votingPopulation: 5400,
    favoredVotePct: 71.0,
    isWin: true,
    congVisitCount: 1,
    coordinatorUids: ["coord-04"],
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: "brgy-004",
    name: "Santo Niño",
    districtId: "dist-01",
    districtName: "North District",
    population: 18321,
    votingPopulation: 11200,
    favoredVotePct: 55.0,
    isWin: true,
    congVisitCount: 2,
    coordinatorUids: ["coord-01"],
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: "brgy-005",
    name: "San Jose",
    districtId: "dist-04",
    districtName: "West District",
    population: 11500,
    votingPopulation: 7800,
    favoredVotePct: 45.8,
    isWin: false,
    congVisitCount: 0,
    coordinatorUids: ["coord-05"],
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
];

export const mockCoordinators: Coordinator[] = [
    {
        id: "coord-01",
        name: "Juan Dela Cruz",
        address: "123 Rizal St, Quezon City",
        contact: "09171234567",
        districtId: "dist-01",
        status: "active",
        assignedBrgyIds: ["brgy-001", "brgy-004"],
        lastReportAt: new Date() as any,
        reportCount: 12,
        updatedAt: new Date() as any,
    },
    {
        id: "coord-02",
        name: "Maria Clara",
        address: "456 Mabini Ave, Manila",
        contact: "09209876543",
        districtId: "dist-01",
        status: "active",
        assignedBrgyIds: ["brgy-001"],
        lastReportAt: new Date() as any,
        reportCount: 8,
        updatedAt: new Date() as any,
    },
    {
        id: "coord-03",
        name: "Jose Rizal",
        address: "789 Bonifacio St, Pasig",
        contact: "09181112233",
        districtId: "dist-02",
        status: "inactive",
        assignedBrgyIds: ["brgy-002"],
        lastReportAt: null,
        reportCount: 0,
        updatedAt: new Date() as any,
    }
]
